// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uGTKGHAJVMXm8ZgFsPiEnc
// Component: dOFxKjzAm8
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariants_77XwrmqHkCl8I } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 77XwrmqHKCl8i/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_sta_draghi.module.css"; // plasmic-import: uGTKGHAJVMXm8ZgFsPiEnc/projectcss
import sty from "./PlasmicOhMyLord.module.css"; // plasmic-import: dOFxKjzAm8/css

export const PlasmicOhMyLord__VariantProps = new Array();

export const PlasmicOhMyLord__ArgProps = new Array();

export const defaultOhMyLord__Args = {};

function PlasmicOhMyLord__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultOhMyLord__Args, props.args);
  const $props = args;
  const $ctx = ph.useDataEnv?.() || {};
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_77XwrmqHkCl8I()
  });

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___2Olc6
            )}
          >
            {
              "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. "
            }
          </div>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___9TjS
            )}
          >
            {"Oh"}
          </div>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__bdzeS
            )}
          >
            {"my"}
          </div>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__l9OWa
            )}
          >
            {"Lord!"}
          </div>

          <p.PlasmicImg
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(sty.img)}
            displayHeight={"485px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"713px"}
            loading={"lazy"}
            src={{
              src: "/plasmic/sta_draghi/images/_844Da0Eb089248CfA13E3Fc528Eb2308Jpg.jpeg",
              fullWidth: 805,
              fullHeight: 538,
              aspectRatio: undefined
            }}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__uem3X
            )}
          >
            {
              "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. "
            }
          </div>

          <p.Stack
            as={"div"}
            data-plasmic-name={"freeBox"}
            data-plasmic-override={overrides.freeBox}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___5Cqio
              )}
            >
              <React.Fragment>
                <React.Fragment>{""}</React.Fragment>
                <h6
                  className={classNames(
                    projectcss.all,
                    projectcss.h6,
                    projectcss.__wab_text,
                    sty.h6__cW3Hn
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__sKnUv
                      )}
                    >
                      {"Pro"}
                    </h5>
                    <React.Fragment>{"Doris Priesching"}</React.Fragment>
                  </React.Fragment>
                </h6>
                <React.Fragment>
                  {
                    "\nAls Bridgerton 2020 startete, war ich fassungslos. Frauen, deren alleiniger Zweck es ist, sich hübsch rauszuputzen, um am Heiratsmarkt Chancen zu haben? Männer, die als Herren der Schöpfung antanzen, geboren, Verantwortung zu übernehmen, für Hab und Gut und zuletzt für die hinter ihnen hertrippelnden Schnattergänse? Verrat am Feminismus! Ich schob die Begei-sterung auf Weihnachten, den Lockdown, der Herzen und Hirne des Publikums weich gemacht haben musste. Meine feministische Welt war damals noch in Ordnung.\n\nZwei Jahre später bestimmt die Pandemie noch immer unser Leben. Jedes Mal, wenn ich dachte, jetzt haben wir es über-standen („Omikron ist der Gamechanger.“ Haha), geschah das exakte Gegenteil. Nichts wurde besser. Winter, kalt, grau, eintönig, infektiös. Was für eine Mischung!\n\nUnd jetzt ist da wieder Bridgerton, die zweite Staffel. Ich habe alle Folgen gesehen und nehme alles zurück. "
                  }
                </React.Fragment>
              </React.Fragment>
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__vsvcs
              )}
            >
              <React.Fragment>
                <React.Fragment>{""}</React.Fragment>
                <h6
                  className={classNames(
                    projectcss.all,
                    projectcss.h6,
                    projectcss.__wab_text,
                    sty.h6___8A7Yv
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5___4SKr9
                      )}
                    >
                      {"Contra"}
                    </h5>
                    <React.Fragment>{"Nana Siebert"}</React.Fragment>
                  </React.Fragment>
                </h6>
                <React.Fragment>
                  {
                    "\nWenn Sie dem aufgeregten Geschnatter im Freundeskreis folgen, dann beschleicht Sie bei der Erwähnung von Bridgerton fast so was wie Fomo, die „fear of missing out“ – also die Angst, etwas zu verpassen? Gemach! Ehe Sie ein Netflix-Abo abschließen und über acht neuen Folgen Bridgerton exakt 464 Minuten Ihrer Lebenszeit verschwenden, gibt es hier einen wertvollen Tipp: Googeln Sie das schriftstellerische Œuvre der amerikanischen Autorin Julia Quinn, Verfasserin der achtteiligen Bridgerton-Buchreihe. Wer sich die Umschläge von Werken wie Mein wildes, ungezähmtes Herz oder Wie verführt man einen Lord anschaut, hat die Ästhetik der Serie erfasst: Herz, Schmerz, Drama und ganz viel Romantik.\n\nAuf dieser groschenromanigen Kitschspur wandeln eine Reihe von heiratsfähigen Frauen der britischen High Society durch die aufwendig-schrillen Kulissen von Luftschlössern, allen voran die liebliche Edwina Sharma (Charithra Chandran), die erst kürzlich von Bombay nach London gekommen ist. "
                  }
                </React.Fragment>
              </React.Fragment>
            </div>
          </p.Stack>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "img", "freeBox"],
  img: ["img"],
  freeBox: ["freeBox"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicOhMyLord__ArgProps,
      internalVariantPropNames: PlasmicOhMyLord__VariantProps
    });

    return PlasmicOhMyLord__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicOhMyLord";
  } else {
    func.displayName = `PlasmicOhMyLord.${nodeName}`;
  }
  return func;
}

export const PlasmicOhMyLord = Object.assign(
  // Top-level PlasmicOhMyLord renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    freeBox: makeNodeComponent("freeBox"),
    // Metadata about props expected for PlasmicOhMyLord
    internalVariantProps: PlasmicOhMyLord__VariantProps,
    internalArgProps: PlasmicOhMyLord__ArgProps
  }
);

export default PlasmicOhMyLord;
/* prettier-ignore-end */
